# Generated by Django 3.2 on 2021-07-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20210730_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='Convience',
            field=models.CharField(choices=[('None', 'None'), ('Liberary', 'Liberary'), ('Both', 'Both'), ('Bus', 'Bus')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='Std',
            field=models.CharField(choices=[('v', 'v'), ('ix', 'ix'), ('vi', 'vi'), ('iv', 'iv'), ('i', 'i'), ('viii', 'viii'), ('ii', 'ii'), ('vii', 'vii'), ('x', 'x'), ('iii', 'iii')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myform',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
